### ISSUE TITLE
Closing card doesn't always redraw screen

### ISSUE THREAD

**Issue by NetMage** [rpetrich/ProSwitcher#139] opened 2009-12-23 04:03 UTC
Sometimes closing the righost card leaves blank space in
middle of screen but a tap causes screen redraw with card in middle

**Comment by sysrage** [comment] 2009-12-24 06:21
Issue 142 is a dupe to this....

I can't reproduce this every single time, but I can make it happen often enough to be able to get you any data you need. Just let me know what you need. Unfortunately, I don't yet have a consistent way to reproduce it. I just randomly backgrounded a ton of apps, closed them, backgrounded a bunch more, closed them in a different order, etc. etc. Eventually, it happened again. Here's screenshot of what we mean:

http://img94.imageshack.us/img94/6545/flowchatupload925257370.jpg

Another note: When taking that screenshot, the 'flash' that turns the screen white when you take screenshots got stuck on the screen too. Tapping the screen made the flash clear and PS fixed itself.

**Comment by sstarr07** [comment] 2010-01-14 03:38
I get this bug too...w. the latest release b4

**Comment by sysrage** [comment] 2010-01-14 03:50
This is fixed in the latest build for me.

**Comment by sstarr07** [comment] 2010-01-14 04:13
Really? Most of the time I slide up to close an app, it leaves a blank space...

**Comment by sysrage** [comment] 2010-01-14 05:10
The way I had found to consistently reproduce the problem no longer causes it for me. Do you have a certain combination of steps to reproduce it every time?

**Comment by sstarr07** [comment] 2010-01-14 05:17
Well its when ever I close Cydia, umm a game...it jus leaves a blank space.

**Comment by rpetrich** [comment] 2010-01-15 21:01
Can anyone confirm if the close button is still visible, or if it disappears as well? (after triggering the bug and then deactivating and reactivating PS)

Perhaps what is happening is that the app isn't closing when we "ask it politely to close" and should set a timer that kills it if it doesn't close in time...

**Comment by sysrage** [comment] 2010-01-15 22:18
When this used to happen to me, the close button was not still visible. There was no card, no buttons, no text name, no icon. I haven't had it happen in any of the RC's, though.

**Comment by sstarr07** [comment] 2010-01-15 23:13
This still happens to me w. the latest beta. When I slide the card up nothing shows, no button, no text, no icon, simply a blank and I could only see the cards beside the blank spaces. As soon as I touch the blank spot it takes me back to an open card.

EDIT: this occurs the most when you try to slide the LAST card up.

**Closed as completed** 2010-06-22 22:56 UTC
Labels: More Info Needed
