### ISSUE TITLE
Phone App

### ISSUE THREAD

**Issue by Surenix** [rpetrich/ProSwitcher#14] opened 2009-12-13 19:00 UTC
Switch to turn off the Phone app from showing because it backgrounds auto and the screenshot remains blank for some reason? Maybe a delay in before the screenshot is generated?

**Comment by grp** [comment] 2009-12-19 02:06
The Phone app has many bugs; this is just one of them.

Anyone want to buy me a iPhone so I can fix them :P?

**Comment by rpetrich** [comment] 2009-12-19 10:53
I can't reproduce this one on 3.0 3G S :(
(perhaps I've misunderstood the bug)

**Comment by jerryen** [comment] 2009-12-19 11:45
I think he means it takes the screenshot before the app is done loading like it does to Mail and iPod for me. 
http://cld.ly/aeu64
I'm on 3GS.

**Comment by rpetrich** [comment] 2009-12-19 12:09
Oh, the problem is that Mail, Phone and MobileMusicPlayer don't draw any user-interface while loading in the background at startup. The best we can do here is to use the default image

(note: there may be a way to force them to paint, but I imagine this would use more resources than is necessary; might come as part of "live view updates" and be an option)

**Comment by grp** [comment] 2009-12-22 06:57
Closed as this is dependent on live views, which we aren't really doing atm.

**Closed as completed by grp** 2009-12-22 06:57 UTC
