### ISSUE TITLE
"Become Home Screen" feature doesn't Background the app.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#172] opened 2009-12-25 12:10 UTC
## [ProSwitcher 1.0 + libactivator 1.0] [iPhone 3G]

When using the "Become Home Screen" feature and single tap the home button inside an app it doesn't background the current app. This is annoying because I want to use single tap for ProSwitcher like how normally "Short hold" would work.

**Comment by verzel** [comment] 2009-12-26 18:34
Become Home Screen doesn't background the app, but other activation methods do, even with Become Home Screen enabled.

**Comment by GabsNL** [comment] 2009-12-26 19:12
I know this. I also just realized that some people would want to use this to exit an app and quickly open PSW. I'll make a separate Feature Request for Single Tap Activation method.

**Comment by grp** [comment] 2009-12-27 02:09
This should be fixed in the next release.

**Comment by rpetrich** [comment] 2009-12-28 00:02
Removed "Accepted" label as we need to discuss this. This feature was designed this way on purpose because there are a lot of "technically challenged" users who have installed ProSwitcher and won't understand that having a million apps backgrounded at once isn't a good idea. Backgrounding applications when this feature is activated is a bad idea IMO

**Comment by GabsNL** [comment] 2009-12-28 00:08
rPetrich: Thats why I posted this: "I also just realized that some people would want to use this to exit an app and quickly open PSW." And why I made a separate Feature Request for Single tap activation. I think Become Home Screen should stay the same. For people like me or people with an iPod 3G/iPhone 3GS, Single Tap activation would be a blessing.

**Comment by rpetrich** [comment] 2009-12-28 00:11
Single tap activation is a libactivator feature request that won't be implemented as an option in the list. Ever.

**Comment by GabsNL** [comment] 2009-12-28 00:15
rpetrich: :( Truly, single tap activation is the only feature I miss within ProSwitcher. As ProSwitcher is a "Palm Pre App switcher" I think single tap activation is essential. I know a lot of iPhone/iPod users out there really want this feature.

**Comment by verzel** [comment] 2009-12-28 01:18
Why not compromise? Have an option that pops up when Become Home Screen is enabled that allows you to choose whether or not that backgrounds apps.

**Comment by rpetrich** [comment] 2009-12-28 02:24
verzel: a variation on that is what chpwn just proposed in IRC; it will be done.

**Comment by verzel** [comment] 2009-12-28 03:51
good to hear.

**Comment by grp** [comment] 2010-01-02 21:01
Implemented as a setting.

**Closed as completed** 2010-01-27 05:27 UTC
Labels: Completed
