### ISSUE TITLE
Crashes 

### ISSUE THREAD

**Issue by xXFR0STBYTEXx** [rpetrich/ProSwitcher#42] opened 2009-12-17 19:29 UTC
i have it set to open with springboard spread. if you don't let go once its open and slide your finger it will crash to safe mode. Actually its anytime you touch the screen.

**Comment by sysrage** [comment] 2009-12-17 19:49
I can't reproduce this crash, but it does point out interesting behavior.

with activation method 'slide down from status bar' -- if you slide down but don't lift finger, proswitcher comes up and you can then slide your finger left or right and sbsettings will pop up over top. not really a problem, but....

with activation methods 'springboard icon pinch or spread', if you pinch/spread but don't lift fingers, proswitcher comes up, you can then swipe left or right and it switches your springboard page. not a major problem unless you swipe to spotlight. then you have a keyboard on top of proswitcher. you have to enter a search term or close proswitcher. 

probably a libactivator bug. i'll go post it over there.

**Comment by xXFR0STBYTEXx** [comment] 2009-12-18 21:25
alright, and i keep trying and it will always do it, i have it set to spread to open, it opens fine then if you swipe your finger across the screen it will crash. i have nothing running in the background and if you swipe to the left it will crash.

**Comment by rpetrich** [comment] 2009-12-19 11:57
Can you update to the latest libactivator and post a crash log? (use CrashReporter)

**Comment by xXFR0STBYTEXx** [comment] 2009-12-20 08:08
everything is working perfect now.

**Comment by rpetrich** [comment] 2009-12-20 09:02
I will close this then

**Closed as completed by rpetrich** 2009-12-20 09:02 UTC
Labels: Completed
