### ISSUE TITLE
Zoom out x2 Feature Request

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#194] opened 2009-12-28 20:41 UTC
Similar to the Pre, you can zoom out the cards x2 to get a broader view of whats open. Don't know if that's possible, but it would be great to have another x2 Zoomed out view of the cards.

Thanks.

**Comment by grp** [comment] 2009-12-29 04:12
Duplicate of rearrange cards feature request.

**Closed as completed by grp** 2009-12-29 04:12 UTC
