### ISSUE TITLE
Screen turn completely white, force shutdown.

### ISSUE THREAD

**Issue by GabsNL** [rpetrich/ProSwitcher#153] opened 2009-12-24 11:51 UTC
## Steps to reproduce this problem:

Try to make a screenshot of issue 139/142 listed on this site.
## Result/issue

The screen flashes white and stays that way. 
I could reproduce this problems every time I did this.
Screenhot: http://img63.imageshack.us/img63/6595/img0232.png
The Lockscreen is also completely white, yet when I 'slide to unlock' I can still hear the unlock sound. When switching the ringer switch on and off it still shows that graphic.
Screenshot: http://img686.imageshack.us/img686/9132/ringer.png
Only way to get out of this is Force shutdown, by holding the home and power button for a few seconds at the same time.

**Comment by sysrage** [comment] 2009-12-24 14:23
Just tapping the screen got rid of the flash for me, but yes, it's a problem. :)

**Comment by GabsNL** [comment] 2009-12-27 00:58
Still there in 1.0. As syrage said tapping the screen takes it away, but not always (for me at least).

**Comment by grp** [comment] 2009-12-27 02:03
I've never seen this.

Can someone that gets this list your MS plugins and your firmware version?

**Comment by sysrage** [comment] 2009-12-27 02:28
This issue, 139, and 142 are all the same root cause I believe.. I can get it to happen fairly regularly, but not every time. iPhone 3GS with 3.1.2 firmware and following MS extensions:

ActionMenu, LibActivator, Backgrounder, BatteryControl, ClockHide, CyDelete, Safari Download Manager, FiveIconDock, LockInfo, Stack, PopupBlocker, PreferenceLoader, PrivaCy, ProSwitcher, ReflectiveDock, Snappy, UserAgent Faker, 3G Unrestrictor, WinterBoard, iRealSMS 3.0, LibHide, Notifier, Mailto Attachments

Like I said, I can reproduce this fairly regularly. Hit me up on IRC if there's any debugging I can do for you.

**Comment by GabsNL** [comment] 2009-12-27 02:37
@sysrage Damn that list is HUGE! :p
Mine; Phone 3G FW: 3.1.2
MS: libactivator, Backgrounder, Bosspaper, CategoriesSB, libhide, Preferenceloader and ProSwitcher

**Comment by rpetrich** [comment] 2009-12-27 23:19
Is this related to which libactivator events are set?
Can someone experiencing this bug please disable all events from both ProSwitcher and OverBoard (if installed) and then try one-by-one?

**Comment by GabsNL** [comment] 2009-12-28 00:34
rpetrich: I just disabled all the Activation Methods and turned on "Become Home Screen" and quickly closed iPod and Mail by using swipe up and it still got stuck. Making a screenshot of it made my screen stay on the white flash. Tapping it removed it do.

**Comment by sysrage** [comment] 2009-12-28 01:23
Found the following steps reproduce this issue every time:

1) re-spring
2) open stocks app
3) activate PS
4) tap background to close PS
5) open weather app
6) activate PS
7) swipe up weather app to close it
8) swipe up the next app that shows to close it (for me, it's mail.app)

At that point, the card doesn't slide to the next app (stocks). If I take a screenshot, it gets stuck in the 'flash' (white screen) until I tap the screen. The phone will not go into sleep mode while in bugged state.

This is on a 3GS with push mail enabled, so the default apps that are backgrounded are Phone and Mail (sometimes iPod shows up on the list but doesn't seem to matter for this bug).

**Comment by ghost** [comment] 2009-12-28 01:42
I can reproduce it on my 3Gs as well with Sysrage's above steps.

**Comment by rpetrich** [comment] 2009-12-28 02:20
sysrage: thanks for reposting this here. your assistance in IRC has been most helpful :)

**Closed as completed** 2010-01-20 07:03 UTC
Labels: More Info Needed
