### ISSUE TITLE
Crashes and puts in safe mode

### ISSUE THREAD

**Issue by TsotsiHak** [rpetrich/ProSwitcher#116] opened 2009-12-22 11:02 UTC
After the 0.7.5 upgrade, there is a crash bug. When you open an app and activate ProSwitcher while the app is loading, it crashes to safe mode. It wasn't doing this before 0.7.5

**Comment by rpetrich** [comment] 2009-12-22 12:11
Confirmed and fixed in latest unstable

**Comment by TsotsiHak** [comment] 2009-12-22 12:30
It's still crashing. I'm not the only one having this problem. It wasn't doing this in 0.7.3

**Comment by rpetrich** [comment] 2009-12-22 13:05
That's because we haven't released the update yet. I can't just magically change the code running on your phone

**Comment by ghost** [comment] 2009-12-22 13:30
Geez Ryan... You better upgrade your iPhone programming skills then ;)

**Comment by TsotsiHak** [comment] 2009-12-22 13:35
LOL at you smart asses. I only made my first comment^^^^^because he closed the issue. LOL i like a sense of humor though.

**Closed as completed** 2009-12-23 00:50 UTC
Labels: Completed

**Comment by TsotsiHak** [comment] 2009-12-23 03:08
0.8 no more crashing. Thanks
