### ISSUE TITLE
App Hangs

### ISSUE THREAD

**Issue by blsub6** [rpetrich/ProSwitcher#262] opened 2010-01-29 19:52 UTC
periodically, when unlocking while app is running in the background, the app hangs and continues to function normally but cannot be quit without being forced.  While looking at the hanging app, ProSwitcher doesn't activate.  It's almost like the app sticks as the home screen.  I usually just end up having to kill the process with SBSettings

**Comment by rpetrich** [comment] 2010-01-30 00:50
Does this occur with just Backgrounder running?

**Comment by blsub6** [comment] 2010-01-31 08:12
I can't reproduce this consistently but it happens often enough to be annoying.  It usually happens when I lock my phone with an app still running in the background and then unlock later.  I have proswitcher's 'Become Home Screen' setting set to 'Background' so it almost seems like proswitcher sets the 'stuck' app as the homescreen instead of itself.

I've also noticed that I cannot quit the 'stuck' app by doing the normal 'force quit' (hold power, wait till 'slide to power off' slider appears then hold home button).  I have to either respring or kill the process with SBSettings.

**Comment by sysrage** [comment] 2010-01-31 17:21
Sounds very much like the Backgrounder issue that's been around for a VERY long time. I'm guessing the author isn't going to ever bother fixing it.

http://code.google.com/p/iphone-backgrounder/issues/detail?id=173&colspec=ID%20Type%20Status%20Summary

**Comment by blsub6** [comment] 2010-02-01 06:22
I understood that I didn't answer Ryan's question after I had posted that long-ass reply lol

I'm not sure if it happens with only backgrounder running.  I looked at that like that sysrage posted and it sounds extremely similar but I wasn't able to reproduce it using the methods they described there.  What they describe in that thread is my problem though and if it is a problem with backgrounder...well that really sucks

**Comment by mede** [comment] 2010-02-04 02:08
I have the exact same issue..  That's why I came here.. 

Also, exactly same case of not being able to reproduce it every time..  Just a me too post and will be investigating as well.  

Hadn't happened before libactivator 1.2 even ONCE (in regard to being backgrounder's fault comment).  I refer to activator, because I installed proswitcher 1.1 before activator 1.2 and didn't have the problem back then.  Have to go to sbsettings/processes to kill the process as well.

Is there a way to enable debug logging in Proswitcher?? even by plist modification?

**Comment by mede** [comment] 2010-02-04 02:20


**Comment by sysrage** [comment] 2010-02-04 15:10
mede's "bug" sounds absolutely nothing like the one be and blsub were talking about. those re-create steps don't mention a thing about the backgrounded app becoming the home screen. in fact, they say the opposite in that neither the app or PS become the home screen.

**Comment by blsub6** [comment] 2010-02-04 18:52
Alright, I just removed the ProSwitcher and Activator packages and tried to reproduce the bug with just Backgrounder installed using the methods described in sysrage's first post (background app, receive call, end call, backgrounded app is stuck).  It worked.  The problem is with Backgrounder, not ProSwitcher.  It never became apparent to me until now because I didn't use Backgrounder as much as I do now thanks to ProSwitcher.

So Mr. Petrich, rest easy; this is not your problem.  Thank you for an amazing program.  I'm off to find Backgrounder's author to complain to him/her

**Comment by mede** [comment] 2010-02-04 20:19
Damn. Sorry for spamming. Just that the two bugs started appearing at the sane time. Deleting comment and opening new issue.

**Closed as completed** 2010-02-15 17:28 UTC
