### ISSUE TITLE
SBSetting free memory and memoryinfo 

### ISSUE THREAD

**Issue by warcopolo** [rpetrich/ProSwitcher#65] opened 2009-12-20 04:45 UTC
when i use memoryinfo to free memory

iphone go to safe mode...

**Comment by verzel** [comment] 2009-12-20 05:41
That's due to iphone's protective mechanisms kicking in, and mobilesubstrate detects it sometimes and goes into safe mode.  The memory clearing action from SBSettings is a little weird, because it seems to take up all the memory in the phone, clear it, and free it.  iPhone sometimes sees this as an app taking up all the memory, and kills it.

**Comment by grp** [comment] 2009-12-20 06:06
Duplicate of other bug.

**Closed as completed by grp** 2009-12-20 06:06 UTC
Labels: Completed

**Comment by rpetrich** [comment] 2009-12-20 09:19
The free memory command in SBSettings stresses the "memory warning" code of all running applications; ProSwitcher 0.7's low memory code had a crashbug that has been fixed in 0.7.2
