### ISSUE TITLE
Chews through Battery

### ISSUE THREAD

**Issue by Sonola777** [rpetrich/ProSwitcher#103] opened 2009-12-21 22:24 UTC
Love this app but it eats through my 3gs's battery like fire through wood! Was using Kirikae before this and its power usage is no where near as high as this.

**Comment by grp** [comment] 2009-12-21 23:05
That isn't helpful. Unless ProSwitcher is active, it uses no more battery than Kirikae...if you were using it constantly, of course it would, there is more gfx, but otherwise, no.

**Comment by Sonola777** [comment] 2009-12-21 23:17
I beg to differ, I was using my phone like I normally do and noticed that since I started using ProSwitcher my battery lasts about 30% less.

**Comment by grp** [comment] 2009-12-21 23:48
...and I know that there is no technical way that this could happen...

**Comment by dharris** [comment] 2009-12-22 00:41
Have done some comparisons and see virtually no difference between kirikae, PS and MF in terms of battery life.

**Comment by grp** [comment] 2009-12-22 02:01
Now, leave them all running and ProSwitcher will be in the middle :P (below kirikae and above multiflow)

**Comment by xxxjaycexxx** [comment] 2009-12-22 06:04
Hi,
I had noticed the same behavior. I don't have any active push (email, calendar) and usually battery last one day or two.
I installed proswitcher and I used it  a couple of times and I left the phone in sleep mode (I am sure I had more than 50% battery available as I had recharged it during the day)
after about 45 mns - or maybe 1 hour, I could no longer turn on the phone.
I started panicking as there was no reason for this to occur.... but after a while I plugged it to the electric outlet and it appears that the battery was completely down.
I cannot give exact step to reproduce but there is definitely an issue here.
This is a great app but battery consumption is definitely a major issue.

I think I did not notice the battery issue because during the day I was close to my computer and I saw the battery was down, I had recharged it but in less than 3 or 4 hours, my battery was empty again.

THanks

**Comment by rpetrich** [comment] 2009-12-22 06:18
This happens in general with applications that disable sleep mode on the phone because they connect to a network service or the developer is lazy... when backgrounded they will still disable sleep mode

<sup>Note: Sleep mode is different from screen off. In sleep mode, the display, CPU and WiFi network are all powered off; with screen off only the screen is</sup>

**Closed as completed by rpetrich** 2009-12-22 06:18 UTC
Labels: Won't Fix

**Comment by xxxjaycexxx** [comment] 2009-12-22 06:42
Hi
An additional information that may be useful.
I had installed PS but Backgrounder was not installed.
Hope that helps.

**Comment by rpetrich** [comment] 2009-12-22 06:46
jayce: unfortunately there is nothing actionable in your report. did you perhaps leave ProSwitcher activated when you turned off your phone? Is it perhaps conflicting with another extension you have installed? (those are the only possibilities I can think of)

**Comment by xxxjaycexxx** [comment] 2009-12-22 06:46
@rpetrich.
about your note "Note: Sleep mode is different from screen off. In sleep mode, the display, CPU and WiFi network are all powered off; with screen off only the screen is"

from my viewpoint, sleep mode is when I press on the power button to get the screen off.
Is there a different way to get the phone to  switch to "sleep mode" ? I would be glad to know about that.
Thanks

**Comment by rpetrich** [comment] 2009-12-22 13:04
Sleep mode refers to the hardware sleep state, screen on/off refers to the power to the screen. Usually sleep mode is engaged about 30 seconds after the display powers down, but apps have the option of disabling that (including backgrounded apps)
