### ISSUE TITLE
In-app activation/choice

### ISSUE THREAD

**Issue by sstarr07** [rpetrich/ProSwitcher#133] opened 2009-12-22 23:45 UTC
Feature Request:

Instead of PS activating within an app suddenly, is it possible to give the user 2 options: (a) activate PS. (b) switch between apps.

Thanks

**Comment by grp** [comment] 2009-12-22 23:59
Uh...what does that mean?

**Comment by sstarr07** [comment] 2009-12-23 00:02
meaning...right now, when you're in an app, and activate PS it closes the app, goes to springboard, and brings up PS app selection...instead of this can we have PS open with 2 options: 1. activate PS as it does currently and 2. an option to simply not BG the current app and bring up PS to switch to a different app...

hope that was understandable =S

**Comment by grp** [comment] 2009-12-23 00:03
Why not just close it when it comes up? Not going to fix this, this is by design.

**Closed as completed by grp** 2009-12-23 00:03 UTC
Labels: ZFeature Request, Won't Fix

**Comment by rpetrich** [comment] 2009-12-23 00:04
The current behaviour is how we've designed it and is more correct IMO.

**Comment by sstarr07** [comment] 2009-12-23 00:05
Alryt, cool. Thanks
